version: "3.7"
services:
  nodeA:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:master}"
    ports:
      - "11323:1323"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    volumes:
      - "./node-A/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "./node-A/data:/opt/nuts/data:rw"
      - "../tls-certs/nodeA-certificate.pem:/opt/nuts/certificate-and-key.pem:ro"
      - "../tls-certs/truststore.pem:/opt/nuts/truststore.pem:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
  issuer:
    image: nginx:1.25.1
    ports:
      - "10443:443"
    volumes:
      - "./issuer/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../tls-certs/issuer-certificate.pem:/etc/nginx/ssl/server.pem:ro"
      - "../tls-certs/issuer-certificate.pem:/etc/nginx/ssl/key.pem:ro"
      - "../tls-certs/truststore.pem:/etc/nginx/ssl/truststore.pem:ro"
      - "./issuer/html:/etc/nginx/html:ro"
